name: df_safer_dart_flutter_example
publish_to: none
environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  df_safer_dart:
    path: ../../
dev_dependencies:
  flutter_lints: ^6.0.0
